# Generated by Django 2.2.4 on 2020-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minute',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='second',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.CharField(max_length=2),
        ),
    ]
