# Generated by Django 2.2.4 on 2020-03-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_auto_20200320_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='logdir',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
