# Generated by Django 2.2.4 on 2020-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='script',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
