# Generated by Django 3.0.4 on 2020-03-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0006_auto_20200320_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cycle',
            field=models.CharField(choices=[('MI', '1분마다'), ('HO', '한시간마다'), ('DA', '하루마다'), ('MO', '달마다')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
