# Generated by Django 3.0.4 on 2020-03-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0007_schedule_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='second',
            new_name='dayoftheweek',
        ),
    ]
